controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_doc:
    path: /swagger
    controller: api_platform.swagger_ui.action

login_check:
    path: /api/login_check
    methods: ['GET', 'POST']

account_creation:
    path: /api/account_creation
    methods: ['POST']
    controller: App\Controller\Auth\AccountCreationController::accountCreation

account_activation:
    path: /api/account_activation/{token}
    methods: ['GET', 'POST']
    controller: App\Controller\Auth\AccountCreationController::activateAccount

verify_account_activation:
    path: /api/check_account_activation/{email}
    methods: ['GET']
    controller: App\Controller\Auth\LoginController::checkAccountActivation

check_if_email_exist:
    path: /api/check_if_email_exist/{email}
    methods: ['GET']
    controller: App\Controller\Auth\LoginController::checkIfEmailExist