controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

login_check:
    path: /api/login_check
    methods: ['GET', 'POST']

account_creation:
    path: /api/account_creation
    methods: ['POST']
    controller: App\Controller\AccountCreationController::accountCreation

account_validation:
    path: /api/account_validation
    methods: ['GET', 'POST']
    controller: App\Controller\AccountCreationController::activateAccount

verify_account_validation:
    path: /api/check_account_validation/
    methods: ['GET']
    controller: App\Controller\CheckAccountActivationController::checkAccountValidation