controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

login_check:
    path: /api/login_check
    methods: ['GET', 'POST']

account_creation:
    path: /api/account_creation
    methods: ['POST']
    controller: App\Controller\AccountCreationController::accountCreation
