controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_doc:
    path: /swagger
    controller: api_platform.swagger_ui.action

login_check:
    path: /api/login_check
    methods: ['GET', 'POST']

account_creation:
    path: /api/account_creation
    methods: ['POST']
    controller: App\Controller\Auth\AccountCreationController::accountCreation

account_validation:
    path: /api/account_validation
    methods: ['GET', 'POST']
    controller: App\Controller\Auth\AccountCreationController::activateAccount

verify_account_validation:
    path: /api/check_account_validation/
    methods: ['GET']
    controller: App\Controller\Auth\LoginController::checkAccountValidation

check_if_email_exist:
    path: /api/check_if_email_exist/
    methods: ['GET']
    controller: App\Controller\Auth\LoginController::checkIfEmailExist