# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # API Platform 
    # JWTCreatedListener configuration
    api_platform.event.jwt_created_listener:
        class: App\EventListener\JWT\JWTCreatedListener
        arguments: [ '@request_stack' ]
        tags:
            - { name: kernel.event_listener, 
                event: lexik_jwt_authentication.on_jwt_created, 
                method: onJWTCreated }
    
    # LoginCheckSubscriber configuration
    api_platform.login_check_subscriber:
        class: App\EventSubscriber\Login\LoginCheckSubscriber
        arguments: ['@App\Validator\EmailValidator', 
                    '@event_dispatcher',
                    '@Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface', 
                    '@App\Repository\UserRepository']
        tags:
            - { name: kernel.event_subscriber, 
                event: kernel.request , 
                method: onKernelRequest }
    
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'




    # # Event dispatcher
    # event_dispatcher:
    #     class: Symfony\Component\EventDispatcher\EventDispatcherInterface
    #     arguments: ['@event_dispatcher']
    #     tags:
    #         - { name: kernel.event_listener, event: kernel.request , method: onKernelRequest }